# Generated by Django 4.0.5 on 2022-08-23 06:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='passwordresetmodel',
            managers=[
                ('tokens', django.db.models.manager.Manager()),
            ],
        ),
    ]
