# Generated by Django 4.0.5 on 2022-07-06 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('percent_complete', models.IntegerField(default=1)),
                ('developers', models.ManyToManyField(blank=True, null=True, related_name='user_task_set', to=settings.AUTH_USER_MODEL)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task_set', to='bugapi.taskmodel')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('end_date'), nulls_last=True)],
            },
        ),
        migrations.AddConstraint(
            model_name='taskmodel',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('developers__isnull', True), ('parent_task__isnull', False)), models.Q(('developers__isnull', False), ('parent_task__isnull', True)), models.Q(('developers__isnull', True), ('parent_task__isnull', True)), _connector='OR'), name='bugapi_taskmodel_developers_or_parent_task'),
        ),
    ]
