# Generated by Django 4.0.5 on 2022-06-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
