# Generated by Django 4.0.5 on 2022-07-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskmodel',
            name='bugapi_taskmodel_developers_or_parent_task',
        ),
    ]
