# Generated by Django 4.0.5 on 2022-07-06 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugapi', '0002_remove_taskmodel_bugapi_taskmodel_developers_or_parent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='user_task_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
