# Generated by Django 4.0.5 on 2022-06-10 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugapi', '0002_alter_taskmodel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='developers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='percent_complete',
            field=models.IntegerField(default=0),
        ),
    ]
