# Generated by Django 4.0.5 on 2022-06-10 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugapi', '0003_taskmodel_developers_taskmodel_owner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskModel',
            new_name='ProjectModel',
        ),
    ]
