# Generated by Django 4.0.5 on 2022-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapi', '0005_alter_projectmodel_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='percent_complete',
            field=models.IntegerField(default=1),
        ),
    ]
