# Generated by Django 4.0.5 on 2022-06-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapi', '0006_alter_projectmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
