# Generated by Django 4.0.5 on 2022-07-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugapi', '0006_alter_messagesmodel_cc_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesmodel',
            old_name='cc_users',
            new_name='cc_to',
        ),
        migrations.RenameField(
            model_name='messagesmodel',
            old_name='to_users',
            new_name='send_to',
        ),
    ]
