# Generated by Django 4.0.5 on 2022-06-16 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('bugapi', '0007_alter_projectmodel_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('end_date'), nulls_last=True)]},
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('percent_complete', models.IntegerField(default=1)),
                ('parent_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_project_set', to='bugapi.projectmodel')),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task_set', to='bugapi.taskmodel')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('end_date'), nulls_last=True)],
            },
        ),
    ]
