# Generated by Django 4.0.5 on 2022-06-16 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugapi', '0008_alter_projectmodel_options_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_project_set', to='bugapi.projectmodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task_set', to='bugapi.taskmodel'),
        ),
    ]
