# Generated by Django 4.0.5 on 2022-07-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapi', '0008_sudousermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudousermodel',
            name='draftbox',
            field=models.ManyToManyField(blank=True, related_name='draftbox', to='bugapi.messagesmodel'),
        ),
    ]
