# Generated by Django 4.0.5 on 2022-08-23 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugapi', '0009_sudousermodel_draftbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudousermodel',
            name='requested_by',
            field=models.ManyToManyField(blank=True, related_name='requested_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sudousermodel',
            name='requesting',
            field=models.ManyToManyField(blank=True, related_name='requesting_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
