# Generated by Django 4.0.5 on 2022-06-19 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugapi', '0010_taskmodel_bugapi_taskmodel_parent_project_or_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='developers',
            field=models.ManyToManyField(related_name='user_task_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
